services:
  app:
    container_name: "synapse_uas_app"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - '${PORT}:${PORT}'
  db:
    container_name: "synapse_uas_db"
    image: postgres:17-alpine
    ports:
      - '${DB_PORT}:${DB_PORT}'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
