export enum ErrorCode {
  UNEXPECTED = 'UNEXPECTED',
  INVALID_DATA = 'INVALID_DATA',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  WRONG_PASSWORD = 'WRONG_PASSWORD',
  USER_CREATE = 'COULD_NOT_CREATE_USER',
  USER_UPDATE = 'COULD_NOT_UPDATE_USER',
  USER_DELETE = 'COULD_NOT_DELETE_USER',
}
